import type { JobResult, Application } from './api';

export const mockJobs: JobResult[] = [
  {
    id: 'mock_1',
    title: 'Senior Python Developer',
    company: 'TechCorp',
    location: 'Remote',
    salary: '$120,000 - $180,000',
    description: 'We are looking for a talented Senior Python Developer to join our team at TechCorp. You will work on cutting-edge projects using modern technologies. Collaborate with cross-functional teams to deliver high-quality software solutions.',
    url: 'https://example.com/jobs/1',
    source: 'linkedin',
    remote: true,
    posted_date: '2 days ago',
    match_score: 92,
    skill_match: 95,
    matched_skills: ['python', 'django', 'rest', 'sql'],
    missing_skills: ['kubernetes'],
  },
  {
    id: 'mock_2',
    title: 'Full Stack Engineer',
    company: 'DataFlow Inc',
    location: 'San Francisco, CA',
    salary: '$130,000 - $170,000',
    description: 'Join DataFlow Inc as a Full Stack Engineer. Build scalable web applications using React and Node.js. Work with a world-class engineering team.',
    url: 'https://example.com/jobs/2',
    source: 'indeed',
    remote: false,
    posted_date: '5 days ago',
    match_score: 85,
    skill_match: 88,
    matched_skills: ['javascript', 'react', 'node.js'],
    missing_skills: ['typescript'],
  },
  {
    id: 'mock_3',
    title: 'Machine Learning Engineer',
    company: 'Neural Labs',
    location: 'Remote',
    salary: '$150,000 - $200,000',
    description: 'Neural Labs is seeking a Machine Learning Engineer to develop and deploy ML models at scale. Work with cutting-edge AI technologies.',
    url: 'https://example.com/jobs/3',
    source: 'remotive',
    remote: true,
    posted_date: '1 day ago',
    match_score: 78,
    skill_match: 82,
    matched_skills: ['python', 'tensorflow', 'data science'],
    missing_skills: ['pytorch', 'nlp'],
  },
  {
    id: 'mock_4',
    title: 'DevOps Engineer',
    company: 'CloudNine Systems',
    location: 'Remote',
    salary: '$110,000 - $160,000',
    description: 'CloudNine Systems is hiring a DevOps Engineer to manage CI/CD pipelines and cloud infrastructure. Experience with AWS and Kubernetes required.',
    url: 'https://example.com/jobs/4',
    source: 'linkedin',
    remote: true,
    posted_date: '3 days ago',
    match_score: 72,
    skill_match: 75,
    matched_skills: ['aws', 'docker', 'linux'],
    missing_skills: ['kubernetes', 'terraform'],
  },
  {
    id: 'mock_5',
    title: 'Backend Developer (Python)',
    company: 'AppMatrix',
    location: 'Austin, TX',
    salary: '$100,000 - $150,000',
    description: 'AppMatrix needs a Backend Developer with strong Python skills. Build APIs and microservices for our growing platform.',
    url: 'https://example.com/jobs/5',
    source: 'indeed',
    remote: false,
    posted_date: '1 week ago',
    match_score: 88,
    skill_match: 90,
    matched_skills: ['python', 'flask', 'postgresql', 'api'],
    missing_skills: ['graphql'],
  },
  {
    id: 'mock_6',
    title: 'Data Engineer',
    company: 'DataSphere',
    location: 'Remote',
    salary: '$115,000 - $165,000',
    description: 'DataSphere is looking for a Data Engineer to design and build data pipelines. Work with large-scale data processing systems.',
    url: 'https://example.com/jobs/6',
    source: 'remotive',
    remote: true,
    posted_date: '4 days ago',
    match_score: 68,
    skill_match: 70,
    matched_skills: ['python', 'sql', 'aws'],
    missing_skills: ['spark', 'kafka'],
  },
  {
    id: 'mock_7',
    title: 'Frontend Developer',
    company: 'PixelPerfect',
    location: 'New York, NY',
    salary: '$90,000 - $140,000',
    description: 'PixelPerfect is seeking a Frontend Developer with React expertise. Create beautiful, responsive user interfaces.',
    url: 'https://example.com/jobs/7',
    source: 'linkedin',
    remote: false,
    posted_date: '6 days ago',
    match_score: 65,
    skill_match: 68,
    matched_skills: ['javascript', 'react', 'html', 'css'],
    missing_skills: ['next.js', 'typescript'],
  },
  {
    id: 'mock_8',
    title: 'AI Engineer',
    company: 'BrightAI',
    location: 'Remote',
    salary: '$140,000 - $190,000',
    description: 'BrightAI is building the future of artificial intelligence. Join us as an AI Engineer working on LLMs and generative AI.',
    url: 'https://example.com/jobs/8',
    source: 'remotive',
    remote: true,
    posted_date: '1 day ago',
    match_score: 80,
    skill_match: 83,
    matched_skills: ['python', 'machine learning', 'deep learning'],
    missing_skills: ['llm', 'transformers'],
  },
  {
    id: 'mock_9',
    title: 'Site Reliability Engineer',
    company: 'SysArc',
    location: 'Seattle, WA',
    salary: '$125,000 - $175,000',
    description: 'SysArc is hiring an SRE to ensure system reliability and performance. Experience with monitoring and incident response required.',
    url: 'https://example.com/jobs/9',
    source: 'indeed',
    remote: false,
    posted_date: '2 weeks ago',
    match_score: 60,
    skill_match: 62,
    matched_skills: ['linux', 'docker', 'python'],
    missing_skills: ['prometheus', 'grafana', 'kubernetes'],
  },
  {
    id: 'mock_10',
    title: 'Software Architect',
    company: 'NextGen Tech',
    location: 'Remote',
    salary: '$160,000 - $220,000',
    description: 'NextGen Tech needs a Software Architect to design scalable systems. Lead technical decisions and mentor engineering teams.',
    url: 'https://example.com/jobs/10',
    source: 'linkedin',
    remote: true,
    posted_date: '3 days ago',
    match_score: 75,
    skill_match: 78,
    matched_skills: ['python', 'aws', 'microservices'],
    missing_skills: ['graphql', 'kafka'],
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app_1',
    job_title: 'Senior Python Developer',
    company: 'TechCorp',
    location: 'Remote',
    salary: '$120,000 - $180,000',
    match_score: 92,
    status: 'interview',
    applied_date: '2026-04-20T10:30:00',
    notes: 'Phone interview scheduled for next week',
    job_url: 'https://example.com/jobs/1',
    source: 'linkedin',
  },
  {
    id: 'app_2',
    job_title: 'Full Stack Engineer',
    company: 'DataFlow Inc',
    location: 'San Francisco, CA',
    salary: '$130,000 - $170,000',
    match_score: 85,
    status: 'applied',
    applied_date: '2026-04-22T14:15:00',
    notes: '',
    job_url: 'https://example.com/jobs/2',
    source: 'indeed',
  },
  {
    id: 'app_3',
    job_title: 'DevOps Engineer',
    company: 'CloudNine Systems',
    location: 'Remote',
    salary: '$110,000 - $160,000',
    match_score: 72,
    status: 'rejected',
    applied_date: '2026-04-18T09:00:00',
    notes: 'Position filled internally',
    job_url: 'https://example.com/jobs/4',
    source: 'linkedin',
  },
  {
    id: 'app_4',
    job_title: 'Machine Learning Engineer',
    company: 'Neural Labs',
    location: 'Remote',
    salary: '$150,000 - $200,000',
    match_score: 78,
    status: 'interview',
    applied_date: '2026-04-23T11:45:00',
    notes: 'Technical interview passed, waiting for final round',
    job_url: 'https://example.com/jobs/3',
    source: 'remotive',
  },
  {
    id: 'app_5',
    job_title: 'Backend Developer (Python)',
    company: 'AppMatrix',
    location: 'Austin, TX',
    salary: '$100,000 - $150,000',
    match_score: 88,
    status: 'offer',
    applied_date: '2026-04-15T16:30:00',
    notes: 'Offer received! Reviewing compensation package.',
    job_url: 'https://example.com/jobs/5',
    source: 'indeed',
  },
];

export const mockResume = {
  name: 'Alex Developer',
  email: 'alex.dev@email.com',
  phone: '(555) 123-4567',
  location: 'San Francisco, CA',
  linkedin: 'https://linkedin.com/in/alexdev',
  github: 'https://github.com/alexdev',
  summary: 'Experienced software engineer with 5+ years in full-stack development. Passionate about building scalable systems and working with modern technologies.',
  skills: [
    'python', 'javascript', 'typescript', 'react', 'node.js', 'django',
    'flask', 'fastapi', 'postgresql', 'mongodb', 'redis', 'aws',
    'docker', 'kubernetes', 'git', 'github', 'ci/cd', 'linux',
    'sql', 'rest', 'graphql', 'html', 'css', 'tailwind',
    'tensorflow', 'machine learning', 'data science',
  ],
  experience: [
    { title: 'Senior Software Engineer', company: 'Tech Solutions Inc', description: 'Led development of microservices architecture serving 1M+ users.' },
    { title: 'Full Stack Developer', company: 'StartupXYZ', description: 'Built MVP from scratch, grew to 100K users within 6 months.' },
  ],
  education: [
    { degree: 'B.S. Computer Science', field: 'Software Engineering' },
  ],
};

export const mockStatistics = {
  applications: {
    total: 5,
    pending: 0,
    applied: 1,
    rejected: 1,
    interview: 2,
    offer: 1,
    accepted: 0,
    declined: 0,
    response_rate: 80,
    interview_rate: 60,
    avg_match_score: 83,
  },
  resume_loaded: true,
  skills_count: 24,
  current_matches: 10,
};

export const mockRecommendations = [
  { type: 'skill_gap', message: 'Consider learning "kubernetes" - mentioned in 8 job postings', priority: 'high' },
  { type: 'profile', message: 'Add your LinkedIn profile to improve visibility to recruiters', priority: 'medium' },
  { type: 'search', message: 'Try searching for: "python react node.js"', priority: 'low' },
];

export const mockWeeklyActivity = [
  { week: 'W14', applied: 3, responses: 1 },
  { week: 'W15', applied: 5, responses: 2 },
  { week: 'W16', applied: 2, responses: 0 },
  { week: 'W17', applied: 7, responses: 3 },
];
